# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fac33c8ab65283ce9eece9630065a79d8bc0c5660f26610b3e79755ce8c0477dffed871bc50a6b950431f3ce484a15c2a3c306ed58f8ee03392c434ae08320f

test:
  secret_key_base: 1cbe1a644986de75a87450ef81ed5c9260bfe73a1256ab6a641e015bca47db0685575d9c24661080068b7c8d6335c4b7e3412fa42dc98fff16ffac180ee4e5f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
